// Snapshot shared/model-index-sources/<benchmark>.json: { benchmark, version, index, label, updated, rows: [{ model, effort, value, source_url, retrieved_at, kind, interval?, cost_per_task?, cost_benchmark?, cost_source?, harness?, price? }] }.
// Writes shared/model-index-data.ts from the snapshots; --print writes it to stdout instead.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const dir = join(root, "shared/model-index-sources");
const target = join(root, "shared/model-index-data.ts");

const VENDOR = {
  "platform.claude.com": "Anthropic API pricing",
  "ai.google.dev": "Gemini API pricing",
  "dev.meta.ai": "Meta Model API pricing",
  "developers.openai.com": "OpenAI API pricing",
  "docs.x.ai": "xAI API pricing",
};

const HEADER = `// Generated by scripts/model-index/build-data.mjs from shared/model-index-sources. Do not edit; edit the snapshots and rebuild.
export type ModelIndexKey = "intelligence" | "coding" | "agentic" | "general" | "legal" | "cost";

/** USD per 1M tokens. */
export interface ModelRates {
  input: number;
  cachedInput: number;
  output: number;
}

export interface ModelPrice extends ModelRates {
  /** Last day of a promotional price; \`next\` applies from \`next.from\`. */
  until?: string;
  next?: ModelRates & { from: string };
  /** This price covers prompts up to this many tokens; \`above\` covers longer ones. */
  upToTokens?: number;
  above?: ModelRates;
}

export interface ModelIndexEntry {
  provider: string;
  /** Wink model id; Antigravity ids drop their -high/-medium/-low suffix. */
  model: string;
  label: string;
  /** "all": the source publishes one value per model (list prices, LegalBench). */
  effort: string;
  index: ModelIndexKey;
  /** Source precision. Blended USD per 1M tokens for \`cost\`, the benchmark's own scale otherwise. */
  score: number;
  price?: ModelPrice;
  /** USD per task from the same run as the score. */
  cost?: number;
  costBenchmark?: ModelIndexBenchmark;
  costSource?: string;
  /** 95% interval, in the score's scale. */
  interval?: { low: number; high: number };
  source: string;
  sourceLabel: string;
  benchmark: ModelIndexBenchmark;
  version: string | null;
  kind: "independent" | "vendor";
  harness?: string;
  retrievedAt: string;
}

export interface ModelIndexSource {
  index: ModelIndexKey;
  version: string | null;
  label: string;
  /** The source's own last-updated date; null when it publishes none. */
  updated: string | null;
  /** Oldest retrieval among the rows. */
  retrievedAt: string;
}
`;

const literal = (value) =>
  value instanceof Object
    ? `{ ${Object.entries(value)
        .filter(([, v]) => v !== undefined)
        .map(([k, v]) => `${k}: ${literal(v)}`)
        .join(", ")} }`
    : JSON.stringify(value);

function priceLabel(row) {
  const vendor = VENDOR[new URL(row.source_url).hostname];
  if (!vendor) throw new Error(`no vendor name for ${row.source_url}`);
  const notes = [
    row.price.upToTokens && `prompts up to ${row.price.upToTokens / 1000}k tokens`,
    row.price.until && `promo price through ${row.price.until}`,
  ].filter(Boolean);
  return `${[vendor, ...notes].join(", ")} (USD per 1M tokens)`;
}

function buildData() {
  const models = JSON.parse(readFileSync(join(dir, "models.json"), "utf8"));
  const snapshots = readdirSync(dir)
    .filter((name) => name.endsWith(".json") && name !== "models.json")
    .sort()
    .map((name) => JSON.parse(readFileSync(join(dir, name), "utf8")));
  const entries = [];
  const sources = {};
  for (const snap of snapshots) {
    for (const row of snap.rows) {
      const meta = models[row.model];
      if (!meta) throw new Error(`${snap.benchmark}: no provider or label for ${row.model}`);
      const { price } = row;
      entries.push({
        provider: meta.provider,
        model: row.model,
        label: meta.label,
        effort: row.effort,
        index: snap.index,
        score: price ? (7 * price.cachedInput + 2 * price.input + price.output) / 10 : row.value,
        price,
        cost: row.cost_per_task,
        costBenchmark: row.cost_benchmark,
        costSource: row.cost_source,
        interval: row.interval,
        source: row.source_url,
        sourceLabel: price ? priceLabel(row) : snap.label,
        benchmark: snap.benchmark,
        version: snap.version,
        kind: row.kind,
        harness: row.harness,
        retrievedAt: row.retrieved_at,
      });
    }
    const oldest = snap.rows.map((row) => row.retrieved_at).sort((a, b) => Date.parse(a) - Date.parse(b))[0];
    sources[snap.benchmark] = { index: snap.index, version: snap.version, label: snap.label, updated: snap.updated, retrievedAt: oldest };
  }
  const newest = Math.max(...entries.map((entry) => Date.parse(entry.retrievedAt)));
  return [
    HEADER,
    `export type ModelIndexBenchmark = ${Object.keys(sources).map((id) => JSON.stringify(id)).join(" | ")};`,
    "",
    `export const MODEL_INDEX_AS_OF = ${JSON.stringify(new Date(newest).toISOString().slice(0, 10))};`,
    "",
    "export const MODEL_INDEX_SOURCES = {",
    ...Object.entries(sources).map(([id, source]) => `  ${JSON.stringify(id)}: ${literal(source)},`),
    "} satisfies Record<ModelIndexBenchmark, ModelIndexSource>;",
    "",
    "export const MODEL_INDEX_ENTRIES: ModelIndexEntry[] = [",
    ...entries.map((entry) => `  ${literal(entry)},`),
    "];",
    "",
  ].join("\n");
}

if (process.argv.includes("--print")) process.stdout.write(buildData());
else writeFileSync(target, buildData());
